name: Rust CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy, rustfmt
        override: true

    - name: update Rust
      run: make install
 
    - name: Build Rust
      run: make release

    - name: Format
      run: make format

    - name: Lint
      run: make lint

    - name: Test
      run: make test



